name: build-portfolio-file

on:
  push:
    paths:
      - img/portfolio-images/**

jobs:
  buildUpdatedPortfolio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run:
          echo "date=$(date +'%Y-%m-%d')"

      - name: Create file
        run:
          cp ".templates/portfolio-template.html" "outputTests/portfolio.html"
          cd img/portfolio-images/
          for FILE in $(ls)
          do
          echo "<li><img class="shadow" src="$FILE" alt="" /></li>" >> portfolio.html
          done
          #echo "</ul></body></html>" >> portfolio.html

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: Update to current image folder
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: "img/portfolio-images"
          push: true