name: build-portfolio-file

on:
  push:
    paths:
      - img/portfolio-images/**

jobs:
  buildUpdatedPortfolio:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')"

      - name: Create file
        run: |
          cp .templates/portfolio-template.html outputTests/portfolio.html
          cd img/portfolio-images
          for FILE in $(ls)
          do
          echo "<li><img class="shadow" src="$FILE" alt="" /></li>" >> portfolio.html
          done
          echo "</ul></body></html>" >> portfolio.html
          git add .
          git commit -m 'updated-portfolio'
          git push