name: build-portfolio-file

on:
  push:
    paths:
      - img/portfolio-images/**

jobs:
  buildUpdatedPortfolio:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get current date
        id: date
        run:
          echo "date=$(date +'%Y-%m-%d')"

      - name: Create file
        run:
          touch testfile.md
          echo "testing" > testfile.md
          pwd
          
          cp .templates/portfolio-template.html portfolio_build.html
          for FILENAME in $(ls img/portfolio-images/)
          do
          echo "<li><img class=\"shadow\" src=\"img/portfolio-images/$FILENAME\"></li>" >> "portfolio_build.html"
          done
          echo "</ul></body></html>" >> "portfolio_build.html"

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: Update to current image folder
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: "*.html"
          push: true